spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.148.144:3306/mengliangbo_juntai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Mysql_123456

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.guet.weappdemo.mapper


#微信配置
wx:
  pay:
    #微信公众号或者小程序等的appid
    app-id: wx0ce552912c5e4957
    #应用密钥
    app-secret: 1904646f9533ce1993c86e3ad302f504
    #微信支付商户号
    mch-id: 1623889015
    #微信支付商户密钥
    mch-key: v2LZk95bXz6VPjQq9yOPg3wPCD3BKqcM

  login:
    #微信后台授权的url，通过此url发送code、appid、小程序秘钥给微信后台换取openId、session_key等
    url: https://api.weixin.qq.com/sns/jscode2session?appid=wx0ce552912c5e4957&secret=1904646f9533ce1993c86e3ad302f504&js_code={2}&grant_type=authorization_code
    #小程序秘钥
    secret: 1904646f9533ce1993c86e3ad302f504
    #微信公众号或者小程序等的appid
    app-id: wx0ce552912c5e4957
