spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.148.144:3306/mengliangbo_juntai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Mysql_123456

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.guet.weappdemo.mapper


#微信配置
wx:
  pay:
    #微信公众号或者小程序等的appid
    app-id: wx506a7af4825cb208
    #应用密钥
    app-secret: 0b89666bf2c72eaba1f9cd8a7d35fe55
    #微信支付商户号
    mch-id: 1623889015
    #微信支付商户密钥
    mch-key: v2LZk95bXz6VPjQq9yOPg3wPCD3BKqcM
    #回调通知接口
    notify_url: https://477m2288i7.eicp.vip/result

